### ISSUE TITLE
MathML Font Settings doesn't (yet?) support SeaMonkey

### ISSUE THREAD

**Issue by tonymec** [fred-wang/Mathzilla#27]
IMHO the MathML Font Settings extension ought to support SeaMonkey.

The "Add-on Converter" site (see http://forums.mozillazine.org/viewtopic.php?f=40&t=2834855 and http://addonconverter.fotokraina.com/ ) might help, but I don't know if it will be enough.

See also https://developer.mozilla.org/en-US/Add-ons/SeaMonkey_2 about writing extensions for SeaMonkey (and the differences compared to Firefox and Thunderbird).

**Comment by fred-wang** [comment]
I'm closing this issue, since it will be fixed in Gecko 38:
https://bugzilla.mozilla.org/show_bug.cgi?id=1114752#c36

**Comment by fred-wang** [comment]
@tonymec I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1160455
