### ISSUE TITLE
Require Additional Font Option

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [fred-wang/Mathzilla#29]
Can you please add an option to use FreeSerif in MathML Font Settings? I found this font is also suitable to display mathematical formulas.

https://www.gnu.org/software/freefont/ranges/math.html

**Comment by KrasnayaPloshchad** [comment]
By the way, if you found a problem, you can [submit an item](https://savannah.gnu.org/bugs/?group=freefont) at any time, or try to use a fresh release from [here](https://code.launchpad.net/~dns/+recipe/freefont/).

**Comment by fred-wang** [comment]
The fonts in MathML Font settings have an Open Type MATH table (https://github.com/fred-wang/MathFonts). For example does FreeSerif have non-unicode glyphs for stretchy/largeop operators?

**Comment by KrasnayaPloshchad** [comment]
No. FreeSerif is part of [GNU FreeFont](https://www.gnu.org/software/freefont/). GNU FreeFont is Unicode-encoded for compatibility with all modern operating systems, the policy for FreeFont will be to follow as closely as makes sense the Unicode standard for whatever characters are included. They are pleased with the Mathematical Operators range, with which most of the glyphs used in LaTeX can be displayed.

**Comment by fred-wang** [comment]
In that case it won't be appropriate to display e.g. underbraces or big integrals. I'd prefer that by default the add-on only suggests fonts with an Open Type MATH table and not "only" math characters. Maybe I can add add an option to make the list in the context menu configurable. Note that you can already change the font family in the preference of the add-on.

**Comment by KrasnayaPloshchad** [comment]
Oh~I understand, I don't know about it, I think maybe they have shown on the usage.txt file in their package.

**Comment by KrasnayaPloshchad** [comment]
Well, which page using MathML is require OpenType MATH table?

**Comment by fred-wang** [comment]
Here is one:

      <math>
        <munder>
          <mo>⏟</mo>
          <mspace width="40em"/>
        </munder>
      </math>

which should render like this

![brace](https://cloud.githubusercontent.com/assets/567455/7003195/d96ef562-dc56-11e4-95c3-5dcee5f12bac.png)

and not like this

![brace2](https://cloud.githubusercontent.com/assets/567455/7003217/1d5bb724-dc57-11e4-94a9-c9a192904d40.png)

or worse, with a tofu character...

Note that Gecko has various fallback methods (using a scale transform to draw integrals bigger, using another font like STIX to draw the braces etc). However, you may use &l;math style="font-family: FreeSerif"&gt; (or as said above, set the font-family in the preference of the add-on) and clear the font.mathfont-family option in "about:config" if you want to be sure that other fonts are not used.

**Comment by fred-wang** [comment]
Another test: https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/Fonts/Test

**Comment by fred-wang** [comment]
Here is the expected result:
![test2](https://cloud.githubusercontent.com/assets/567455/7003329/cb727414-dc58-11e4-8426-25ab6291ef59.png)

and what I get by setting font-family: FreeSerif in the preferences of the "MathML Font Settings" + clearing font.mathfont-family:

![test](https://cloud.githubusercontent.com/assets/567455/7003322/c2cb4c14-dc58-11e4-977c-8fec2ddec9cf.png)

**Comment by KrasnayaPloshchad** [comment]
Well, I have got a development release from [Launchpad](https://code.launchpad.net/~dns/+recipe/freefont/), all of them looks well.

**Comment by fred-wang** [comment]
As I said, it's possible that Gecko uses other fonts (be sure to set the font-family to FreeSerif and to clear the font.mathfont-family in about:config). At least it does not work for the fonts installed on my Debian system.

I think the best to check if a font contains an OpenType Math table is to use fontforge to open that font: https://fontforge.github.io/math.html

**Comment by fred-wang** [comment]
OK, I opened a development release and you're right FreeSerif has an OpenType MATH table:

![freeserif-fontforge](https://cloud.githubusercontent.com/assets/567455/7019841/5152c30c-dd14-11e4-91c2-413d669a5b1e.png)

I'll check the log to see when it was added. Thanks.

**Comment by fred-wang** [comment]
So according to the changelog, the Open Type MATH table was added in November 2013, while the latest release (and the official Debian package) is from 2012. So I'll add FreeSerif into the default list when the next version is released. Do you know when it will happen?

**Comment by fred-wang** [comment]
I asked it:
http://lists.gnu.org/archive/html/freefont-bugs/2015-04/index.html
https://groups.google.com/forum/#!topic/mozilla.dev.tech.mathml/23Fs7Eb8Zd4

**Comment by KrasnayaPloshchad** [comment]
Oh~I don't know when the next version is released. I accessed their project page, found the admin is [Steve White](https://savannah.gnu.org/users/Stevan_White ), maybe you can contect with him.

**Comment by fred-wang** [comment]
OK, I've made the default list of fonts configurable. I've opened #30 to include FreeSerif when the next version is released.

**Comment by fred-wang** [comment]
New version already released:
https://addons.mozilla.org/en-US/firefox/addon/mathml-font-settings/
