### ISSUE TITLE
Very high font (and spacing above and below)

### ISSUE THREAD

**Issue by kunegis** [fred-wang/Mathzilla#33]
![screenshot from 2016-01-05 20 03 48](https://cloud.githubusercontent.com/assets/8511179/12124746/7800a910-b3e7-11e5-8a28-c816c3cd584c.png)

See the uploaded screenshot.  Math text (e.g., on the Wikipedia page "Dedekind number" as in the attached screenshot) has multiple empty lines above and below it. Parentheses are much too high (by a factor of 5 or so), and result in only a few lines of maths being displayed on the full screen.

Using:  
Firefox 43.0
Ubuntu 14.4
MathML-fonts 2.1.1-signed
MathML Font Settings 0.2.1-signed

Settings of MathML Font Settings:
Font family list:  Asana Math, Cambria Math, Latin Modern Math, Lucida Bright Math, Minion Math, Neo Euler, STIX Math, TeX Gyre Bonum Math, TeX Gyre Pagella Math, TeX Gyre Schola Math, TeX Gyre Termes Math, XITS Math
Font family:  [empty setting]
Font scale:  129
Use important rules:  yes

**Comment by fred-wang** [comment]
This is probably because the Ubuntu release contains obsolete fonts without the USE_TYPO_METRICS bit set, see
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1473552
https://bugzilla.mozilla.org/show_bug.cgi?id=1208776

You can install the latest version at
http://www.gust.org.pl/projects/e-foundry/lm-math

**Comment by fred-wang** [comment]
Sorry it is https://bugs.launchpad.net/ubuntu/+source/lmodern/+bug/1502701

**Comment by kunegis** [comment]
Thanks, it worked

For the record, I managed to fix the bug by hand by performing these steps:

* Download the latest version of the Latin Modern Math font from http://www.gust.org.pl/projects/e-foundry/lm-math
* You get a zipfile, unpack it. It contains documentation and a file 'latinmodern-math.otf'. Copy that file to ~/.fonts (which you must create if it doesn't exist yet)
* Restart Firefox

**Comment by fred-wang** [comment]
Glad to hear that. Just an additional remark: the MathML-fonts add-on contains web fonts for Latin Modern Math, but the system version are always tried first if they are available. Unfortunately, the one distributed by Ubuntu doesn't have the use_typo_metris bit, which explains why you saw the bug.
