### ISSUE TITLE
README links to Native MathML should update too

### ISSUE THREAD

**Issue by Fanolian** [fred-wang/Mathzilla#35]
README.md from https://github.com/fred-wang/Mathzilla/tree/master/native-mathml still points to https://addons.mozilla.org/en-US/firefox/addon/mathjax-native-mathml/, which is already 404.

In addition, README.md from https://github.com/fred-wang/Mathzilla should update the description and link for Native MathML.

Thanks you for the extensions.

**Comment by fred-wang** [comment]
Thanks!
