### ISSUE TITLE
Doesn't force MathML on certain sites

### ISSUE THREAD

**Issue by Geremia** [fred-wang/Mathzilla#38]
For example, Native MathML doesn't force MathML on https://math.stackexchange.com. I have to manually select MathML from the MathJax popup.

I'm using Linux Firefox version 45.2.0 and Native MathML 1.8 addon (updated 4/25/2016).

**Comment by Geremia** [comment]
Also, I don't seem to be getting this problem with Firefox 47.0.1.

**Comment by fred-wang** [comment]
Thanks for the report. I also noticed that in the past (it disappears after a page reload) but was not able to find a reliable way to reproduce the issue.

**Comment by Geremia** [comment]
@fred-wang Interestingly, I needed to enable Native MathML in order to get MathML equations on Wikipedia pages to appear. (I have my Wikipedia prefs set to use MathML.) With Native MathML disabled, the MathML equations on Wikipedia would just be whitespace. What exactly did Native MathML do to make the MathML on Wikipedia pages visible? Wikipedia dosen't use MathJax. I'm using Firefox 47.0.1.

**Comment by fred-wang** [comment]
@Geremia Wikipedia now uses MathML with SVG fallback by default (even for non-logged users). It fallbacks to SVG for all browsers but you can easily show the MathML with some CSS rules:

/advancedSettings#CSS_for_the_MathML_with_SVG_fallback_mode

You can do it in your custom Wikipedia user CSS or in the custom user stylesheet of your browsers. The add-on also loads this CSS automatically:

https://github.com/fred-wang/Mathzilla/blob/master/native-mathml/data/mediawiki.css
https://www.mediawiki.org/wiki/Extension:Math

**Comment by Geremia** [comment]
@fred-wang  thanks

Native MathML is working with StackExchange now, too.
