### ISSUE TITLE
native MathML for Android

### ISSUE THREAD

**Issue by physikerwelt** [fred-wang/Mathzilla#39]
I installed FF for Android and tried to install the native MarhML plugin. It downloaded but nothing happened afterwards. Is someone using native MarhML on Android?

**Comment by fred-wang** [comment]
Normally it should work for Android too. I haven't tested it, though

**Comment by fred-wang** [comment]
I does not seem to have many users, compared to the MathML fonts addon:

https://addons.mozilla.org/en-US/firefox/addon/native-mathml/statistics/usage/os/?last=30
https://addons.mozilla.org/en-US/firefox/addon/mathml-fonts/statistics/usage/os/?last=30

**Comment by physikerwelt** [comment]
Do you have an android device? I cound not manage to install the extension.

**Comment by fred-wang** [comment]
I'm currently migrating the addon to WebExtension format (https://developer.mozilla.org/en-US/Add-ons/WebExtensions). This should happen before Mozilla 57. Hopefully that will improve compatibility between browsers & platforms.

I moved the repository to https://github.com/fred-wang/webextension-native-mathml so I'm closing this.

**Comment by fred-wang** [comment]
@physikerwelt Can you please try the latest version (1.9.1)? https://addons.mozilla.org/addon/native-mathml/
