### ISSUE TITLE
Prevents automatical breaking of long expression

### ISSUE THREAD

**Issue by cipri-tom** [fred-wang/Mathzilla#41]
Hi,

With this extension enabled, the equation in [this answer](http://math.stackexchange.com/a/833110/197563) on `math.stackexchange` is not rendered correctly. Disabling the extension allows the formula to be broken onto multiple lines.

With extension:
![screenshot from 2017-02-24 18 17 02](https://cloud.githubusercontent.com/assets/2991890/23313310/82d269a0-fabd-11e6-931b-221f3b2fb889.png)

Without extension:
![screenshot from 2017-02-24 18 16 19](https://cloud.githubusercontent.com/assets/2991890/23313324/8a542c18-fabd-11e6-9439-2a5110cea5ca.png)

Can this be fixed ? Thank you!

I believe this can offer an idea: https://github.com/readium/readium-shared-js/issues/279

**Comment by fred-wang** [comment]
Thanks for the report.

The add-on is intended to make things more native so I personally don't plan to add hacks to workaround browser bugs. References:
https://bugs.webkit.org/show_bug.cgi?id=110070
https://bugzilla.mozilla.org/show_bug.cgi?id=534962

However, a separate add-on could be created, similar to https://addons.mozilla.org/en-US/firefox/addon/mathml-mml3ff/ (which BTW should be converted to https://github.com/fred-wang/Mathzilla/issues/24 and migrated to WebExtension) to add such hacks.

**Comment by cipri-tom** [comment]
7 YEARS !! I wouldn't have imagined this is so old ! I understand your position, then; they really should fix it. Sorry I didn't research it properly
