### ISSUE TITLE
Support Firefox v57+

### ISSUE THREAD

**Issue by HaleTom** [fred-wang/Mathzilla#42]
Thanks for this great plugin!

Would you consider supporting Firefox Quantum?

**Comment by fred-wang** [comment]
@HaleTom Which plugin are you talking about? This repository is obsolete, WebExtension versions of each addon have been moved to individual github repo. See the README: https://github.com/fred-wang/Mathzilla#mathzilla ; I expect they work in the most recent versions of Firefox.

**Comment by HaleTom** [comment]
Sweet! I'm really glad I asked. Thanks a bunch!

Is there a trick to installing these and receiving updates given the versions at https://addons.mozilla.org are outdated?

Am I right in thinking that
* https://github.com/fred-wang/webextension-image-to-mathml/

doesn't work with Firefox Quantum, or is it the Firefox Addon page which needs updating:

* https://addons.mozilla.org/en-US/firefox/addon/image-to-mathml/

**Comment by fred-wang** [comment]
OK. Right, I think the image-to-mathml addon was marked experimental on AMO and so I did not spend time to rewrite it using WebExtension format.
